export enum CommonStrings {
  delete = 'Delete',
  cancel = 'Cancel',
  close = 'Закрыть',
  save = 'Save',
  ok = 'Ok',
  submit = 'Подтвердить',
  title = 'Title',
  description = 'Description',
  color = 'Цвет',
  country = 'Country',
  city = 'City',
  timezone = 'Timezone',
  currency = 'Currency',
  day = 'Day',
  week = 'Week',
  month = 'Month',
  year = 'Year',
  settings = 'Settings',
  logout = 'Выход'
}
